//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BienDong()
        {
            this.BienDong_QuyTrinh = new HashSet<BienDong_QuyTrinh>();
            this.BienDongDoanViens = new HashSet<BienDongDoanVien>();
        }
    
        public int BienDongId { get; set; }
        public string TenBienDong { get; set; }
        public string MoTa { get; set; }
        public int LoaiHinhToChucId { get; set; }
        public Nullable<bool> IsChanged { get; set; }
        public string FolderUpload { get; set; }
        public Nullable<bool> ShowList { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BienDong_QuyTrinh> BienDong_QuyTrinh { get; set; }
        public virtual LoaiHinhToChuc LoaiHinhToChuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BienDongDoanVien> BienDongDoanViens { get; set; }
    }
}
