//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienDongDoanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BienDongDoanVien()
        {
            this.BienDong_DoanVien_Map = new HashSet<BienDong_DoanVien_Map>();
        }
    
        public int Id { get; set; }
        public int BienDongId { get; set; }
        public Nullable<System.DateTime> NgayBienDong { get; set; }
        public string QuyetDinh { get; set; }
        public string NoiDung { get; set; }
        public Nullable<short> TrangThaiXuLy { get; set; }
        public int IdCapToChucNhan { get; set; }
        public int IdToChucNhan { get; set; }
        public int NhanVienNhap { get; set; }
        public Nullable<int> ToChucNhap { get; set; }
        public string DsDoanVien { get; set; }
        public string FileDinhKem { get; set; }
    
        public virtual BienDong BienDong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BienDong_DoanVien_Map> BienDong_DoanVien_Map { get; set; }
    }
}
