//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienDong_QuyTrinh_ChiTiet
    {
        public int Id { get; set; }
        public int QuyTrinhId { get; set; }
        public int LoaiHinhToChucId { get; set; }
        public int CapToChucId { get; set; }
        public string Sms { get; set; }
        public string Email { get; set; }
    
        public virtual BienDong_QuyTrinh BienDong_QuyTrinh { get; set; }
    }
}
