//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienDong_DoanVien_Map
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BienDong_DoanVien_Map()
        {
            this.BienDongDoanVienChiTiets = new HashSet<BienDongDoanVienChiTiet>();
        }
    
        public int Id { get; set; }
        public int BienDongDoanVienId { get; set; }
        public int DoanVienId { get; set; }
    
        public virtual BienDongDoanVien BienDongDoanVien { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BienDongDoanVienChiTiet> BienDongDoanVienChiTiets { get; set; }
    }
}
