//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienDongDoanVienChiTiet
    {
        public int Id { get; set; }
        public int BienDongDoanVienId { get; set; }
        public int IdToChucGui { get; set; }
        public int IdToChucNhan { get; set; }
        public System.DateTime NgayThucHien { get; set; }
        public string NoiDung { get; set; }
        public string FileDinhKem { get; set; }
        public int NhanVienXuLy { get; set; }
        public Nullable<short> TrangThai { get; set; }
    
        public virtual BienDong_DoanVien_Map BienDong_DoanVien_Map { get; set; }
    }
}
