//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiThuChi
    {
        public int LoaiThuChiId { get; set; }
        public string TenLoaiThuChi { get; set; }
        public string MoTa { get; set; }
    }
}
