//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDungBangCap_Map
    {
        public int Id { get; set; }
        public int NguoiDungId { get; set; }
        public int BangCapId { get; set; }
        public int LoaiBangCapId { get; set; }
        public int ChuyenNganhId { get; set; }
        public int LoaiHinhDaoTaoId { get; set; }
        public string ThoiGianDaoTao { get; set; }
        public string NamTotNghiep { get; set; }
        public string TruongCapBang { get; set; }
        public string DanhHieu { get; set; }
        public string KetQua { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual BangCap BangCap { get; set; }
        public virtual ChuyenNganh ChuyenNganh { get; set; }
        public virtual LoaiBangCap LoaiBangCap { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
