//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung_ToChuc
    {
        public int Id { get; set; }
        public int ToChucId { get; set; }
        public int NguoiDungId { get; set; }
        public Nullable<int> ChucVuId { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DonViToChuc_Map DonViToChuc_Map { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
