//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhomMau
    {
        public int NhomMauId { get; set; }
        public string TenNhomMau { get; set; }
        public Nullable<int> ThuTu { get; set; }
    }
}
