//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyenMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuyenMenu()
        {
            this.NhomQuyenMenu_Map = new HashSet<NhomQuyenMenu_Map>();
        }
    
        public int QuyenMenuId { get; set; }
        public string TenQuyen { get; set; }
        public string UrlQuyen { get; set; }
        public Nullable<int> QuyenCha { get; set; }
        public Nullable<int> ThuTu { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Class { get; set; }
        public string Styles { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhomQuyenMenu_Map> NhomQuyenMenu_Map { get; set; }
    }
}
