//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhPhanGiaDinh
    {
        public int ThanhPhanGiaDinhId { get; set; }
        public string TenThanhPhanGiaDinh { get; set; }
        public int ThuTu { get; set; }
    }
}
