//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TieuChiGiaoUoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TieuChiGiaoUoc()
        {
            this.NoiDungTieuChiGiaoUocs = new HashSet<NoiDungTieuChiGiaoUoc>();
        }
    
        public int Id { get; set; }
        public int IdGiaoUoc { get; set; }
        public string NoiDung { get; set; }
        public Nullable<bool> OpenChiTiet { get; set; }
    
        public virtual GiaoUocThiDua GiaoUocThiDua { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoiDungTieuChiGiaoUoc> NoiDungTieuChiGiaoUocs { get; set; }
    }
}
