//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vt_ChiPhiSuaXe
    {
        public int id { get; set; }
        public System.DateTime ngayNhap { get; set; }
        public string vatTu { get; set; }
        public Nullable<int> soLuong { get; set; }
        public string donViTinh { get; set; }
        public Nullable<double> donGia { get; set; }
        public Nullable<double> thanhTien { get; set; }
        public string ghiChu { get; set; }
    }
}
