//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vt_DangKiemGiayToXe
    {
        public int id { get; set; }
        public int idXeVanTai { get; set; }
        public string maSoXe { get; set; }
        public string kiemDinhSo { get; set; }
        public Nullable<System.DateTime> ngayKiemDinh { get; set; }
        public string loaiKiemDinh { get; set; }
        public string noiDung { get; set; }
        public Nullable<System.DateTime> ngayHetHan { get; set; }
        public string ghiChu { get; set; }
        public string daXoa { get; set; }
    }
}
