//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vt_DichVuKinhDoanhKhac
    {
        public int id { get; set; }
        public int loaiDichVuKhac { get; set; }
        public System.DateTime ngayHoanThanh { get; set; }
        public string tenCongTrinh { get; set; }
        public string doiTruong { get; set; }
        public Nullable<double> doanhThu { get; set; }
        public Nullable<double> chiPhi { get; set; }
        public Nullable<double> loiNhuan { get; set; }
        public Nullable<double> thanhToanLan1 { get; set; }
        public Nullable<double> thanhToanLan2 { get; set; }
        public Nullable<double> thanhToanLan3 { get; set; }
        public Nullable<double> no { get; set; }
        public string ghiChu { get; set; }
    }
}
