//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vt_LaiXe
    {
        public int id { get; set; }
        public string maLaiXe { get; set; }
        public string tenLaiXe { get; set; }
        public string diaChi { get; set; }
        public string soDienThoai { get; set; }
        public Nullable<int> daXoa { get; set; }
    }
}
