//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vt_LichTrinhXe
    {
        public int id { get; set; }
        public string maChuyen { get; set; }
        public int idLaiXe { get; set; }
        public int idKhachHang { get; set; }
        public System.DateTime thoiGianLapPhieu { get; set; }
        public string noiDungLamViec { get; set; }
        public string noiDi { get; set; }
        public string noiDen { get; set; }
        public Nullable<double> giaChuaThue { get; set; }
        public Nullable<double> thueVat { get; set; }
        public Nullable<double> tongThanhToan { get; set; }
        public Nullable<int> tinhTrangThanhToan { get; set; }
        public Nullable<bool> checkPhieu { get; set; }
        public Nullable<int> daXoa { get; set; }
    }
}
