//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vt_XeSuaChuaTaiXuong
    {
        public int id { get; set; }
        public System.DateTime ngayThang { get; set; }
        public int idXeVanTai { get; set; }
        public int idKhachHang { get; set; }
        public string noiDungSuaChua { get; set; }
        public Nullable<int> soLuong { get; set; }
        public string donViTinh { get; set; }
        public Nullable<double> donGia { get; set; }
        public Nullable<double> thanhTienChuaThue { get; set; }
        public Nullable<double> thueVat { get; set; }
        public Nullable<double> tongThanhToan { get; set; }
        public Nullable<double> no { get; set; }
        public Nullable<double> canTru { get; set; }
        public string ghiChu { get; set; }
    }
}
