//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vt_XeVanTai
    {
        public int id { get; set; }
        public string maSoXe { get; set; }
        public int idLaiXe { get; set; }
        public string daXoa { get; set; }
    }
}
